# =============================================
# Application
# =============================================
spring.application.name=cv-project

# =============================================
# DataSource - PostgreSQL (Render)
# =============================================
spring.datasource.url=jdbc:postgresql://dpg-d7uc01hj2pic739p2ef0-a.oregon-postgres.render.com:5432/db_cv_project
spring.datasource.username=db_cv_project_user
spring.datasource.password=Q3T0tojvBK4bvQ8JlOvwxDr9EV1LLCae
spring.datasource.driver-class-name=org.postgresql.Driver

# =============================================
# JPA / Hibernate
# =============================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# =============================================
# Connection Pool (HikariCP)
# =============================================
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=5

# =============================================
# JWT
# =============================================
security.jwt.secret=8r4x7k2p9m1v5t3q6w8z0a2s4d6f8g1h
security.jwt.expiration-ms=3600000
security.refresh-token.expiration-ms=604800000
