# =============================================
# Profile: dev (AWS)
# =============================================

spring.port=${SERVER_PORT}

spring.datasource.url=jdbc:postgresql://${DB_ENDPOINT}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

security.jwt.secret=${JWT_SECRET}
security.jwt.expiration-ms=${JWT_EXPIRATION:3600000}
security.refresh-token.expiration-ms=${REFRESH_TOKEN_EXPIRATION:604800000}
